# Site settings
title: "CME 213: Introduction to Parallel Computing using MPI, openMP, and CUDA"
email: darve@stanford.edu
description: "Course materials and notes for Stanford class CME 213, Winter 2020"
baseurl: ""
url: "https://stanford-cme213.github.io"
github_username: stanford-cme213
github:
    gradescope_url: https://www.gradescope.com/courses/78093

theme: jekyll-theme-cayman
