# Site settings
title: "CME 213: Introduction to Parallel Computing using MPI, openMP, and CUDA"
email: darve@stanford.edu
description: "Course materials and notes for Stanford class CME 213, Spring 2019"
baseurl: ""
url: "https://stanford-cme213.github.io"
github_username: stanford-cme213

theme: jekyll-theme-cayman
